### PR TITLE
update so that all loglevels are controlled by the same env variable

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by itewk** [comment]
@brenton @liggitt could I get a review and hopefully merge on this PR?

**Comment by itewk** [comment]
@brenton @liggitt is there someone else I should reach out to to get a peer review?

**Comment by brenton** [comment]
Hi @itewk, I apologize for the delay.  This PR was opened while I was on paternity leave and I failed to notice it after I was back.

I'm actually surprised this repo is wired up to our full CI suite.  This doesn't officially ship with the product and is more of a reference.  In any case,

/ok-to-test

**Comment by itewk** [comment]
@brenton thanks for the review and merge.

**Pull request merged**
