### PR TITLE
documenation - many updates

### LINKED ISSUE #27: README needs to be clearer on manual procedure vs automated ansible procedure
@briantward with all of your latest updates that @brenton just merged, reading through the readme I can no longer tell the correct procedure to follow to get this up an running in production.

I think it would be best to seperate the read me into three distinct sections:

1) shared setup
2) automated ansible install (new steps)
3) manual install (previous steps)

And then I think maybe moving the RH-SSO parts to a completely different doc since no one will or should use those in production.

I think the key is our main read me story should be something that is useable in production but now if I am reading the doc I can't tell which steps I need to actually do to get things running as the ansible, rh-sso, and the other manual steps are all mixed together.

### PR DESCRIPTION
**Pull request by itewk**
make the documentation easier to follow.

this will resolve: https://github.com/openshift/request-header-saml-service-provider/issues/27

### CODE REVIEW

**Comment by itewk** [comment]
@briantward please review

**Comment by briantward** [comment]
Added some further updates and changes, submitted it directly to you: https://github.com/itewk/request-header-saml-service-provider/pull/1

Haven't tested it all out yet.  Just there for review.  Will update you shortly.

**Comment by briantward** [comment]
Looks good.  I have a few follow up tweaks that I'll submit in another PR.

@brenton this is ready for merge

**Comment by itewk** [comment]
thank you

**Pull request merged**
