### PR TITLE
add debug docker image with mod_auth_mellon-diagnostics module installed and enabled

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by itewk** [comment]
@brenton @liggitt could I get a review and hopefully merge on this PR?

**Comment by itewk** [comment]
@brenton here is another one for your review.

**Comment by brenton** [comment]
Now this is really useful.  I'm a little worried of a bit of the copy 'n paste from the httpd configuration standpoint.  Would you be willing to find some way to reduce the duplication?

I would suggest using a multi-stage image build similar to what is describe in https://medium.com/@tonistiigi/advanced-multi-stage-build-patterns-6f741b852fae where it discusses "Development/test helper for minimal production stage".  You'd update the main Dockerfile and build the normal image first, then a secondary stage would add in the config for the diagnostics module and use sed to enable it in the correct stanza.

**Comment by itewk** [comment]
@brenton will do...When I get back from PTO.

**Comment by itewk** [comment]
@brenton i have been trying to understand how this multi-stage build works. I think i get it. But I also think its incompatible with doing the docker build in OCP. I have been using this to build the images:

```
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: saml-service-provider
    name: saml-service-provider
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: saml-service-provider
    name: saml-service-provider
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: saml-service-provider:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /
      git:
        ref: debug-image
        uri: https://github.com/itewk/request-header-saml-service-provider.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 5
```

```
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: saml-service-provider-debug
    name: saml-service-provider-debug
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: saml-service-provider-debug
    name: saml-service-provider-debug
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: saml-service-provider-debug:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /
      git:
        ref: debug-image
        uri: https://github.com/itewk/request-header-saml-service-provider.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.debug
      type: Docker
    successfulBuildsHistoryLimit: 5
```

But I don't see an option in Openshift to be able to specify the `--target` option which sould be needed to use multistage builds.

Myabe should just have the Dockerfile.debug do a FROM from the Dockerfile?

**Comment by itewk** [comment]
@brenton after some investigation the multi stage build only exists in Docker 17 but OCP uses docker 1.13 so going with a different approach of having the debug image do a FROM from the none debug image

**Comment by itewk** [comment]
@brenton updated the pull request to move all the docker related files under `saml-service-provider` to follow more standard docker dir structure and also updated Docker.debug to layer on top of Docker since multi stage builds doesn't seem to be an option.

**Comment by itewk** [comment]
closing in favor of https://github.com/openshift/request-header-saml-service-provider/pull/17

**Pull request closed without merging**
